import type { Project } from "@/types/content";

/**
 * SAMPLE PROJECTS. Every project below is invented placeholder content that
 * shows how real case studies will look. Replace them with your own jobs
 * (with the client's permission) before launch.
 */
export const projects: Project[] = [
  {
    slug: "family-home-terrace-pu-membrane",
    title: "Terrace waterproofing for a three-storey bungalow",
    outcome: "Ceiling leaks stopped and a cooler top floor.",
    summary: "Ponding water and cracks on an old terrace were leaking into two top-floor bedrooms.",
    services: ["terrace-roof-waterproofing"],
    propertyType: "residential",
    propertyLabel: "Bungalow",
    area: "goregaon-to-borivali",
    year: "2025",
    areaTreated: "1,850 sq ft",
    duration: "5 days",
    challenge:
      "Water ponded for days after rain because the terrace had lost its slope toward the outlets. Cracks along the parapet junction let water into the slab, staining the ceilings of two bedrooms below.",
    solution: [
      "Removed loose screed and cleaned the slab back to sound concrete",
      "Re-graded the low spots so water runs to the outlets",
      "Built coving along every parapet junction and fitted outlet collars",
      "Applied a reinforced PU membrane with a heat-reflective topcoat",
    ],
    result:
      "The terrace held water through a 48-hour flood test and stayed dry through the next monsoon. The family also noticed a cooler top floor.",
    cover: "terrace-home-after",
    before: "terrace-home-before",
    after: "terrace-home-after",
    gallery: ["terrace-home-before", "terrace-home-after"],
    review: "r-terrace-north",
    featured: true,
    placeholder: true,
  },
  {
    slug: "apartment-bathroom-seepage-repair",
    title: "Stopping bathroom seepage into the flat below",
    outcome: "The neighbour's ceiling dry after full re-waterproofing.",
    summary: "Two bathrooms in a fourth-floor flat were leaking into the flat below.",
    services: ["bathroom-waterproofing", "leakage-detection-repair"],
    propertyType: "residential",
    propertyLabel: "Flat",
    area: "dadar-worli",
    year: "2025",
    areaTreated: "2 bathrooms",
    duration: "7 days",
    challenge:
      "The downstairs neighbour had stains spreading across their ceiling. Pressure tests showed the plumbing was sound — water was getting through failed grout and a membrane that had broken down around the floor traps.",
    solution: [
      "Pressure-tested the supply lines to rule out plumbing",
      "Removed floor tiles and screed in both bathrooms",
      "Applied a liquid membrane across the floors and up the shower walls, with tape at corners and drain collars",
      "Flood-tested for 24 hours, then re-tiled with epoxy grout",
    ],
    result:
      "Both bathrooms passed the flood test, and the neighbour's ceiling dried out and was repainted a few weeks later.",
    cover: "bathroom-apartment-after",
    before: "bathroom-apartment-before",
    after: "bathroom-apartment-after",
    gallery: ["bathroom-apartment-before", "bathroom-apartment-after"],
    review: "r-bathroom-centre",
    featured: true,
    placeholder: true,
  },
  {
    slug: "bungalow-basement-storage-room",
    title: "Dry storage in a bungalow basement",
    outcome: "Active leaks stopped and the basement back in daily use.",
    summary: "Water came through the basement walls every time it rained.",
    services: ["basement-waterproofing", "crack-repair-sealing"],
    propertyType: "residential",
    propertyLabel: "Bungalow",
    area: "thane",
    year: "2024",
    areaTreated: "900 sq ft",
    duration: "6 days",
    challenge:
      "High groundwater pushed water through a vertical crack and the form-tie holes, leaving standing water and salt deposits along the base of every wall.",
    solution: [
      "Injected the leaking crack with water-reactive polyurethane",
      "Plugged and sealed every form-tie hole",
      "Applied a crystalline treatment to the walls and the wall-floor joint",
      "Finished with coving at the base and a sealed floor coating",
    ],
    result: "No water has come in since, and the owners now use the basement for storage and a home gym.",
    cover: "basement-villa-after",
    before: "basement-villa-before",
    after: "basement-villa-after",
    gallery: ["basement-villa-before", "basement-villa-after"],
    review: "r-basement-riverside",
    featured: true,
    placeholder: true,
  },
  {
    slug: "office-roof-membrane-weekend-works",
    title: "Re-roofing an occupied office building over weekends",
    outcome: "Roof leaks fixed with no working days lost.",
    summary: "A failing roof was leaking onto the top-floor office and server room.",
    services: ["commercial-waterproofing", "terrace-roof-waterproofing"],
    propertyType: "commercial",
    propertyLabel: "Office building",
    area: "kurla-ghatkopar-chembur",
    year: "2025",
    areaTreated: "12,000 sq ft",
    duration: "4 weekends",
    challenge:
      "The original membrane had reached the end of its life, with splits around rooftop plant and blocked outlets. The building had to stay fully open during the work.",
    solution: [
      "Surveyed the roof and agreed a weekend-only programme with the facilities team",
      "Removed the failed membrane zone by zone, sealing each zone before Monday",
      "Detailed every plant support, outlet and upstand",
      "Applied a reflective PU-hybrid membrane system",
    ],
    result: "Leaks stopped from the first completed zone, and the building stayed open throughout.",
    cover: "office-roof-after",
    before: "office-roof-before",
    after: "office-roof-after",
    gallery: ["office-roof-before", "office-roof-after"],
    review: "r-office-east",
    featured: true,
    placeholder: true,
  },
  {
    slug: "warehouse-metal-roof-restoration",
    title: "Restoring a leaking warehouse metal roof",
    outcome: "Roof saved from replacement and the stock kept dry.",
    summary: "Corroded fasteners and laps were letting rain onto stored goods.",
    services: ["industrial-waterproofing"],
    propertyType: "industrial",
    propertyLabel: "Warehouse",
    area: "andheri",
    year: "2024",
    areaTreated: "40,000 sq ft",
    duration: "3 weeks",
    challenge:
      "Rust had spread from the fasteners and side laps across the sheets, and several skylight perimeters had failed. Replacing the roof would have meant closing the warehouse.",
    solution: [
      "Treated rust and replaced a handful of perforated sheets",
      "Sealed every fastener and lap with a reinforced sealant",
      "Resealed the skylight perimeters and lined the gutters",
      "Spray-applied an elastomeric roof coating in zones around operations",
    ],
    result:
      "The roof is watertight and protected against further corrosion, at a fraction of the cost of replacement and with no stoppage.",
    cover: "warehouse-roof-after",
    before: "warehouse-roof-before",
    after: "warehouse-roof-after",
    gallery: ["warehouse-roof-before", "warehouse-roof-after"],
    review: "r-warehouse-west",
    featured: true,
    placeholder: true,
  },
  {
    slug: "ground-floor-rising-damp",
    title: "Ending rising damp in a ground-floor living room",
    outcome: "Damp gone, and no more repainting every season.",
    summary: "Paint peeled and salt marks returned on the living-room walls after every repaint.",
    services: ["wall-dampness-treatment"],
    propertyType: "residential",
    propertyLabel: "Ground-floor flat",
    area: "bandra-khar",
    year: "2025",
    areaTreated: "420 sq ft of wall",
    duration: "4 days, plus drying",
    challenge:
      "Moisture was rising through walls with no working damp-proof course, carrying salts that pushed the paint off and left white deposits.",
    solution: [
      "Took moisture readings to confirm rising damp rather than a leak",
      "Injected a chemical damp-proof course into the mortar line",
      "Removed salt-contaminated plaster up to 1 m",
      "Replastered with a breathable, salt-resistant render and breathable paint",
    ],
    result: "Readings fell steadily as the wall dried, and the redecorated walls have stayed clean.",
    cover: "rising-damp-after",
    before: "rising-damp-before",
    after: "rising-damp-after",
    gallery: ["rising-damp-before", "rising-damp-after"],
    review: "r-damp-south",
    placeholder: true,
  },
  {
    slug: "podium-parking-deck-coating",
    title: "Waterproofing a residential podium parking deck",
    outcome: "A dry basement car park and a safer, re-marked deck.",
    summary: "Water was dripping through the podium onto cars parked below.",
    services: ["commercial-waterproofing", "crack-repair-sealing"],
    propertyType: "commercial",
    propertyLabel: "Housing society",
    area: "goregaon-to-borivali",
    year: "2024",
    areaTreated: "18,500 sq ft",
    duration: "3 weeks",
    challenge:
      "Cracks and a failed expansion joint let water through the deck into the basement car park. The deck had to stay partly open for residents.",
    solution: [
      "Phased the work in halves so residents always had parking",
      "Rebuilt the expansion joint with a flexible joint system",
      "Routed and sealed the cracks, then applied a crack-bridging traffic coating",
      "Re-marked the bays, walkways and arrows",
    ],
    result: "The basement car park has stayed dry, and the deck has a cleaner, anti-slip finish.",
    cover: "podium-deck-after",
    before: "podium-deck-before",
    after: "podium-deck-after",
    gallery: ["podium-deck-before", "podium-deck-after"],
    review: "r-podium-north",
    placeholder: true,
  },
  {
    slug: "apartment-block-facade-cracks",
    title: "External wall crack repair for a housing society",
    outcome: "Damp patches gone from eight flats.",
    summary: "Rain was getting through cracks around the windows into residents' bedrooms.",
    services: ["crack-repair-sealing", "wall-dampness-treatment"],
    propertyType: "residential",
    propertyLabel: "Housing society",
    area: "thane",
    year: "2025",
    areaTreated: "9,000 sq ft of facade",
    duration: "12 days",
    challenge:
      "Diagonal cracks from the window corners and gaps at the frame-to-wall joints let wind-driven rain into the walls of eight flats.",
    solution: [
      "Surveyed and mapped every crack from a mobile platform",
      "Routed and sealed the moving cracks with flexible sealant",
      "Resealed window perimeters and added drip edges to the sills",
      "Applied a breathable elastomeric coating across the facade",
    ],
    result: "The interior damp patches dried out and haven't returned, and the building has a fresh, even finish.",
    cover: "facade-cracks-after",
    before: "facade-cracks-before",
    after: "facade-cracks-after",
    gallery: ["facade-cracks-before", "facade-cracks-after"],
    review: "r-facade-riverside",
    placeholder: true,
  },
  {
    slug: "concealed-pipe-leak-detection",
    title: "Tracing a hidden leak above a bedroom ceiling",
    outcome: "Source found without breaking up the floor above.",
    summary: "A spreading ceiling stain had survived two earlier repairs.",
    services: ["leakage-detection-repair"],
    propertyType: "residential",
    propertyLabel: "Flat",
    area: "kurla-ghatkopar-chembur",
    year: "2025",
    areaTreated: "1 bedroom",
    duration: "1 day, plus repair",
    challenge: "Two previous contractors had re-waterproofed the bathroom above, but the stain kept growing.",
    solution: [
      "Mapped moisture across the ceiling and walls",
      "Used thermal imaging to trace the wet path to one corner",
      "Pressure-tested the supply lines and found a leaking concealed joint",
      "Opened a small section, replaced the joint and re-tested",
    ],
    result: "The leak was fixed through one small opening instead of another bathroom rebuild.",
    cover: "ceiling-leak-after",
    before: "ceiling-leak-before",
    after: "ceiling-leak-after",
    gallery: ["ceiling-leak-before", "ceiling-leak-after"],
    review: "r-leak-east",
    placeholder: true,
  },
  {
    slug: "new-build-apartment-basement",
    title: "Built-in waterproofing for a new residential tower",
    outcome: "Basement, wet areas and terraces waterproofed stage by stage.",
    summary: "A developer wanted waterproofing designed in from the foundations.",
    services: ["new-construction-waterproofing", "basement-waterproofing"],
    propertyType: "residential",
    propertyLabel: "New residential tower",
    area: "andheri",
    year: "2024",
    areaTreated: "Basement and 24 wet areas",
    duration: "Across 9 months of construction",
    challenge:
      "The site had a high water table, a two-level basement and 24 bathrooms to protect, with several trades working at once.",
    solution: [
      "Reviewed the drawings and specified a system for each element",
      "Installed external membranes and waterstops on the basement before backfilling",
      "Waterproofed and flood-tested every wet area before tiling",
      "Protected the terrace membranes until handover",
    ],
    result:
      "Every element was inspected and tested before it was covered, and the developer received a complete handover file.",
    cover: "new-build-basement-after",
    before: "new-build-basement-before",
    after: "new-build-basement-after",
    gallery: ["new-build-basement-before", "new-build-basement-after"],
    placeholder: true,
  },
  {
    slug: "restaurant-kitchen-wet-area",
    title: "Overnight kitchen waterproofing for a restaurant",
    outcome: "No more seepage into the shop below, and no lost trading days.",
    summary: "Water from the kitchen floor was leaking into the store underneath.",
    services: ["commercial-waterproofing", "bathroom-waterproofing"],
    propertyType: "commercial",
    propertyLabel: "Restaurant",
    area: "dadar-worli",
    year: "2025",
    areaTreated: "650 sq ft",
    duration: "3 nights",
    challenge:
      "Daily wash-downs had broken down the grout and the membrane around the drain channel, and the restaurant couldn't close.",
    solution: [
      "Worked overnight after service, over three nights",
      "Removed the tiles around the drain channel and re-set it with waterproof collars",
      "Applied a fast-curing membrane with coved skirting",
      "Re-tiled with chemical-resistant epoxy grout",
    ],
    result: "The store below has stayed dry, and the kitchen opened on time every day.",
    cover: "kitchen-floor-after",
    before: "kitchen-floor-before",
    after: "kitchen-floor-after",
    gallery: ["kitchen-floor-before", "kitchen-floor-after"],
    review: "r-kitchen-centre",
    placeholder: true,
  },
  {
    slug: "factory-fire-water-tank",
    title: "Repairing a leaking fire-water tank",
    outcome: "The tank holds water again and passed inspection.",
    summary: "A factory's fire-water tank was losing water through cracks and joints.",
    services: ["industrial-waterproofing", "crack-repair-sealing"],
    propertyType: "industrial",
    propertyLabel: "Factory",
    area: "bandra-khar",
    year: "2024",
    areaTreated: "120,000-litre tank",
    duration: "8 days",
    challenge:
      "The tank was losing water faster than it could be topped up, putting the site's fire-safety compliance at risk.",
    solution: [
      "Drained and cleaned the tank during a planned shutdown",
      "Injected the leaking cracks and treated the construction joints",
      "Applied a crystalline system to the walls and floor",
      "Refilled the tank and monitored the water level",
    ],
    result: "The tank held its level throughout monitoring, and the site passed its fire-safety inspection.",
    cover: "fire-water-tank-after",
    before: "fire-water-tank-before",
    after: "fire-water-tank-after",
    gallery: ["fire-water-tank-before", "fire-water-tank-after"],
    review: "r-tank-south",
    placeholder: true,
  },
];

export const propertyTypes: { id: Project["propertyType"]; label: string }[] = [
  { id: "residential", label: "Residential" },
  { id: "commercial", label: "Commercial" },
  { id: "industrial", label: "Industrial" },
];
