import {
  Activity,
  Award,
  BadgeCheck,
  BrickWall,
  BuildingComplex,
  ClipboardCheck,
  Clock,
  CloudRain,
  Construction,
  Droplets,
  Eye,
  Factory,
  FileText,
  Gauge,
  HardHat,
  Hospital,
  Hotel,
  House,
  LayersArrowDown,
  MapPin,
  PaintRoller,
  Receipt,
  Ruler,
  ScanSearch,
  School,
  ShieldCheck,
  ShowerHead,
  Sparkles,
  SquareParking,
  Sprout,
  Store,
  Sun,
  Target,
  Thermometer,
  Warehouse,
  WavesHorizontal,
  Wind,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import type { IconName } from "@/types/content";

const icons: Record<IconName, LucideIcon> = {
  "cloud-rain": CloudRain,
  "shower-head": ShowerHead,
  "layers-down": LayersArrowDown,
  "brick-wall": BrickWall,
  crack: Activity,
  "scan-search": ScanSearch,
  building: BuildingComplex,
  factory: Factory,
  "hard-hat": HardHat,
  droplets: Droplets,
  waves: WavesHorizontal,
  sprout: Sprout,
  "shield-check": ShieldCheck,
  "clipboard-check": ClipboardCheck,
  "file-text": FileText,
  clock: Clock,
  "sparkle-clean": Sparkles,
  gauge: Gauge,
  thermometer: Thermometer,
  "paint-roller": PaintRoller,
  ruler: Ruler,
  receipt: Receipt,
  target: Target,
  eye: Eye,
  award: Award,
  "badge-check": BadgeCheck,
  house: House,
  store: Store,
  hotel: Hotel,
  school: School,
  hospital: Hospital,
  warehouse: Warehouse,
  parking: SquareParking,
  construction: Construction,
  "map-pin": MapPin,
  wind: Wind,
  sun: Sun,
};

/**
 * Content stores icon names as strings so it stays serialisable (and CMS-friendly).
 * The set deliberately has no people or hands: the site shows buildings, materials and tools only.
 */
export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={1.75} {...props} />;
}
